### ISSUE TITLE
Paste image from clipboard to data URL

### ISSUE THREAD

**Issue by iainelder** [CoderAllan/vscode-imagetodatauri#56]
Currently I use mushan's Paste Image extension for putting images in my Markdown documents.

I like it because I can copy and paste an image from the clipboard.

It works well, but I still have to stop to think about what to call the image file unless I want to accept the generic name.

Sometimes for one-off screenshots I don't even want to create a file. I would just like to paste the data URL and have it rendered.

Does your extension support images stored in the clipboard?

**Comment by CoderAllan** [comment]
At the moment the extension does not have that feature.
But it is a good idea and I will see if I can get it implemented.

Thanks for the idea!

**Comment by CoderAllan** [comment]
I have looked into the Visual Studio Code Clipboard API and it only supports copy/paste of text.
So I looked around and found two extensions that get around this issue:
* https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image 
Solves the issue depending on the operating system, by calling outside the extension either PowerShell, AppleScript or a Linux shell script. I only work on Windows so I could not maintain Linux shell scripts or AppleScript features.
* https://marketplace.visualstudio.com/items?itemName=DarrenDanielDay.screenshot-clipboard
Solves the issue by using a separate custom document in VSCode that accepts the pasted image and from there saves it into a file. It works, but I don't think the solution is very elegant. You could achieve the same result with the same number of click pasting into Paint or another external program. 

The conclusion is that the feature would be great, but at the moment I cannot see a way to implement it and maintain it in an easy to use way.
I suggest that you contact the maintainer of the 'Paste Image' extension and ask if they could implement the 'Paste-as-data-uri' feature in their extension.

**Comment by iainelder** [comment]
Thanks for the feedback and the research!

It seems that screenshot-clipboard's niche is [vscode.dev](https://vscode.dev/), as it avoids any dependencies outside the browser. Good to know, but not my use case.

I'll get in touch with mushan to ask for the feature.

**Comment by iainelder** [comment]
[UNOTES - Markdown Notes WYSIWYG](https://marketplace.visualstudio.com/items?itemName=ryanmcalister.Unotes) has the paste-to-data-URI feature. I just stumbled across it today.

> By default images are embedded as base64 text objects. Images can optionally be auto-converted to local files when pasted.

**Comment by CoderAllan** [comment]
Cool.
Thanks for sharing!
